version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - my-network
    volumes:
      - ./logger:/app/logger
      - ./src:/app/src
      - ./node_modules:/app/node_modules

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - my-network
    volumes:
    - ./pg_data:/var/lib/postgresql/data

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  pgdata:
    driver: local