version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${PORT}
    networks:
      - my-network

  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
      - PGDATA:${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}
    networks:
      - my-network
    volumes:
      - ./pg_data:${PGDATA}

networks:
  my-network:
    name: my-network
    driver: bridge

