
version: '3.8'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - mynetwork
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - /app/node_modules
    restart: always


  postgres:
    container_name: postgres
    build: ./postgres/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - mynetwork
    volumes:
    - database:/var/lib/postgresql/data
    restart: always

volumes:
  database:

networks:
  mynetwork:
    name: mynetwork
    external: false
    driver: bridge

